### ISSUE TITLE
Sometimes get errors when application ends

### ISSUE THREAD

**Issue by alahiff** [simvue-io/python-api#124]
This should be handled properly and not result in an exception.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/psutil-5.9.6-py3.10-linux-x86_64.egg/psutil/__init__.py", line 350, in _init
    self.create_time()
  File "/usr/local/lib/python3.10/dist-packages/psutil-5.9.6-py3.10-linux-x86_64.egg/psutil/__init__.py", line 735, in create_time
    self._create_time = self._proc.create_time()
  File "/usr/local/lib/python3.10/dist-packages/psutil-5.9.6-py3.10-linux-x86_64.egg/psutil/_pslinux.py", line 1650, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/psutil-5.9.6-py3.10-linux-x86_64.egg/psutil/_pslinux.py", line 1877, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/usr/local/lib/python3.10/dist-packages/psutil-5.9.6-py3.10-linux-x86_64.egg/psutil/_pslinux.py", line 1659, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=4523)
```

**Comment by kzscisoft** [comment]
I have not seen this recently so closing
